version: '3'
services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env
    restart: always

  wordpress:
    image: wordpress:5.1.1-php7.3-fpm-alpine
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always  
