plugin: aws_ec2

aws_access_key_id: ********************
aws_secret_access_key: ****************************************
aws_security_token:

regions:
  - ap-northeast-1
hostnames:
  - tag:Name
groups:
  wordpress: "'web-server' in tags.Name"
compose:
  ansible_host: public_ip_address
